/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.twcorpororation.familymart.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import com.twcorpororation.familymart.dao.Conexion;

/**
 *
 * @author Luigui
 */
public class FrmAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdmin.class.getName());

    private int idProductoSeleccionado = -1;

    private int idUsuarioSeleccionado = -1;

    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        initComponents();
        this.setLocationRelativeTo(null); // Para centrar la ventana
        cargarProductos(); // Llena la tabla al abrir la ventana
        cargarIndicadores();
        cargarHistorialVentas(); // Limpia y carga la tabla de ventas
        cargarProductosEliminados(); // Limpia y carga la tabla de eliminados
        cargarGraficoStock();
        cargarUsuarios();

    }

    private void cargarUsuarios() {
        // Al crear el modelo, sobreescribimos el método isCellEditable para que retorne siempre falso
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en todas las celdas
            }
        };

        modelo.addColumn("ID");
        modelo.addColumn("Usuario");
        modelo.addColumn("Rol");
        tblUsuarios.setModel(modelo);

        String sql = "SELECT u.id_usuario, u.username, r.nombre_rol FROM Usuarios u INNER JOIN Roles r ON u.id_rol = r.id_rol WHERE u.estado = 1";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql); java.sql.ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id_usuario"),
                    rs.getString("username"),
                    rs.getString("nombre_rol")
                });
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        }
    }

    private void limpiarCamposUsuarios() {
        txtNomUsuario.setText("");
        txtClave.setText("");
        cbxRol.setSelectedIndex(0);
        idUsuarioSeleccionado = -1;
        txtNomUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtNomUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        cbxRol = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnGuardarUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnLimpiarUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jdFechaInicio = new com.toedter.calendar.JDateChooser();
        jdFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblIngresosTotales = new javax.swing.JLabel();
        lblTotalTransacciones = new javax.swing.JLabel();
        lblAlertasStock = new javax.swing.JLabel();
        lblTicketMaximo = new javax.swing.JLabel();
        lblTicketMinimo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTicketPromedio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEliminados = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnFiltrarFechas = new javax.swing.JButton();
        pnlGraficoStock = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, -1));
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 220, -1));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero" }));
        jPanel1.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 990, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Usuario:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Contraseña:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Rol:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        btnGuardarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarUsuario.setText("GUARDAR USUARIO");
        btnGuardarUsuario.addActionListener(this::btnGuardarUsuarioActionPerformed);
        jPanel1.add(btnGuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 180, 40));

        btnModificarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificarUsuario.setText("MODIFICAR USUARIO");
        btnModificarUsuario.addActionListener(this::btnModificarUsuarioActionPerformed);
        jPanel1.add(btnModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 180, 40));

        btnEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(204, 0, 0));
        btnEliminarUsuario.setText("ELIMINAR USUARIO");
        btnEliminarUsuario.addActionListener(this::btnEliminarUsuarioActionPerformed);
        jPanel1.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 160, 40));

        btnLimpiarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarUsuario.setText("LIMPIAR USUARIO");
        btnLimpiarUsuario.addActionListener(this::btnLimpiarUsuarioActionPerformed);
        jPanel1.add(btnLimpiarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 150, 40));

        jTabbedPane1.addTab("Gestión de Usuarios", jPanel1);

        jLabel1.setText("Código:");

        jLabel2.setText("Nombre del Producto:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Stock:");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel5.setText("Buscar (Nombre o Código):");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Catálogo de Productos", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblVentas);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 490, 350));
        jPanel3.add(jdFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel3.add(jdFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ingresos Totales:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total de Transacciones:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Alertas de Stock:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ticket Más Alto:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Ticket Más Bajo:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        lblIngresosTotales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblIngresosTotales.setText("0");
        jPanel3.add(lblIngresosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 190, -1));

        lblTotalTransacciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalTransacciones.setText("0");
        jPanel3.add(lblTotalTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 180, -1));

        lblAlertasStock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAlertasStock.setText("0");
        jPanel3.add(lblAlertasStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 240, -1));

        lblTicketMaximo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTicketMaximo.setText("0");
        jPanel3.add(lblTicketMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 260, -1));

        lblTicketMinimo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTicketMinimo.setText("0");
        jPanel3.add(lblTicketMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 270, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Ticket Promedio:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        lblTicketPromedio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTicketPromedio.setText("0");
        jPanel3.add(lblTicketPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 280, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Registros eliminados:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        tblEliminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEliminados);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 490, 270));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Venta y control de inventario");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnFiltrarFechas.setText("Filtrar");
        btnFiltrarFechas.addActionListener(this::btnFiltrarFechasActionPerformed);
        jPanel3.add(btnFiltrarFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        javax.swing.GroupLayout pnlGraficoStockLayout = new javax.swing.GroupLayout(pnlGraficoStock);
        pnlGraficoStock.setLayout(pnlGraficoStockLayout);
        pnlGraficoStockLayout.setHorizontalGroup(
            pnlGraficoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficoStockLayout.setVerticalGroup(
            pnlGraficoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(pnlGraficoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 500, 430));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Gráfico:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        jPanel3.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jTabbedPane1.addTab("Dashboard (Reportes)", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String precioStr = txtPrecio.getText().trim();
        String stockStr = txtStock.getText().trim();

        // 1. Validación de campos vacíos
        if (codigo.isEmpty() || nombre.isEmpty() || precioStr.isEmpty() || stockStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Validación de tipos de datos
            double precio = Double.parseDouble(precioStr);
            int stock = Integer.parseInt(stockStr);

            if (precio <= 0 || stock < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser mayor a 0 y el stock no puede ser negativo.", "Rango Inválido", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3. Inserción o Reactivación Inteligente
            // Si el código no existe, hace un INSERT. Si ya existe, hace un UPDATE reactivándolo.
            String sql = "INSERT INTO Productos (codigo_barras, nombre, precio, stock, estado) "
                    + "VALUES (?, ?, ?, ?, 1) "
                    + "ON DUPLICATE KEY UPDATE nombre = ?, precio = ?, stock = ?, estado = 1";

            try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

                // Parámetros para el INSERT
                pstmt.setString(1, codigo);
                pstmt.setString(2, nombre);
                pstmt.setDouble(3, precio);
                pstmt.setInt(4, stock);

                // Parámetros para el UPDATE (por si el código de barras ya existía)
                pstmt.setString(5, nombre);
                pstmt.setDouble(6, precio);
                pstmt.setInt(7, stock);

                pstmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Producto guardado o reactivado correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // 4. Actualizamos todas las tablas visuales
                cargarProductos();
                cargarProductosEliminados(); // Esto hará que el producto desaparezca de la tabla de eliminados
                cargarGraficoStock();
                limpiarCamposProductos();

            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio y el stock deben ser valores numéricos válidos.", "Error de Tipo de Dato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Método para vaciar los campos de texto
    private void limpiarCamposProductos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtCodigo.requestFocus(); // Devuelve el cursor al primer campo para escribir rápido
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCamposProductos();
        idProductoSeleccionado = -1;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int fila = tblProductos.getSelectedRow();
        if (fila >= 0) {
            // Capturamos los datos de la fila seleccionada (columna 0 es el ID)
            idProductoSeleccionado = Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());
            txtCodigo.setText(tblProductos.getValueAt(fila, 1).toString());
            txtNombre.setText(tblProductos.getValueAt(fila, 2).toString());
            txtPrecio.setText(tblProductos.getValueAt(fila, 3).toString());
            txtStock.setText(tblProductos.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (idProductoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();

        try {
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());

            if (precio <= 0 || stock < 0) {
                JOptionPane.showMessageDialog(this, "Valores numéricos inválidos.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String sql = "UPDATE Productos SET codigo_barras=?, nombre=?, precio=?, stock=? WHERE id_producto=?";

            try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, codigo);
                pstmt.setString(2, nombre);
                pstmt.setDouble(3, precio);
                pstmt.setInt(4, stock);
                pstmt.setInt(5, idProductoSeleccionado);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");

                cargarProductos();
                limpiarCamposProductos();
                cargarGraficoStock();

            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese números válidos en Precio y Stock.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (idProductoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este producto?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Cambiamos el estado a 0 (eliminación lógica)
            String sql = "UPDATE Productos SET estado=0 WHERE id_producto=?";

            try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setInt(1, idProductoSeleccionado);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Producto eliminado lógicamente.");

                cargarProductos();
                limpiarCamposProductos();
                cargarGraficoStock();

            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        buscarProductos(txtBuscar.getText().trim());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnFiltrarFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarFechasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        // Llama de vuelta a la ventana de Login
        com.twcorpororation.familymart.FrmLogin login = new com.twcorpororation.familymart.FrmLogin();
        login.setVisible(true);

        // Destruye la ventana actual para liberar memoria
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        // TODO add your handling code here:
        if (idUsuarioSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla.");
            return;
        }

        String usuario = txtNomUsuario.getText().trim();
        String clave = txtClave.getText().trim();
        int idRol = cbxRol.getSelectedItem().toString().equals("Administrador") ? 1 : 2;

        String sql = clave.isEmpty()
                ? "UPDATE Usuarios SET username = ?, id_rol = ? WHERE id_usuario = ?"
                : "UPDATE Usuarios SET username = ?, password = ?, id_rol = ? WHERE id_usuario = ?";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, usuario);
            if (clave.isEmpty()) {
                pstmt.setInt(2, idRol);
                pstmt.setInt(3, idUsuarioSeleccionado);
            } else {
                pstmt.setString(2, clave);
                pstmt.setInt(3, idRol);
                pstmt.setInt(4, idUsuarioSeleccionado);
            }

            pstmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario modificado.");
            cargarUsuarios();
            limpiarCamposUsuarios();
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        if (idUsuarioSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar este usuario?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String sql = "UPDATE Usuarios SET estado = 0 WHERE id_usuario = ?";
            try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setInt(1, idUsuarioSeleccionado);
                pstmt.executeUpdate();
                cargarUsuarios();
                limpiarCamposUsuarios();
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed
        // TODO add your handling code here:
        String usuario = txtNomUsuario.getText().trim();
        String clave = txtClave.getText().trim();
        int idRol = cbxRol.getSelectedItem().toString().equals("Administrador") ? 1 : 2;

        if (usuario.isEmpty() || clave.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Llene todos los campos.");
            return;
        }

        String sql = "INSERT INTO Usuarios (username, password, id_rol, estado) VALUES (?, ?, ?, 1) "
                + "ON DUPLICATE KEY UPDATE password = ?, id_rol = ?, estado = 1";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, usuario);
            pstmt.setString(2, clave);
            pstmt.setInt(3, idRol);
            pstmt.setString(4, clave);
            pstmt.setInt(5, idRol);

            pstmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado/reactivado con éxito.");
            cargarUsuarios();
            limpiarCamposUsuarios();
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = tblUsuarios.getSelectedRow();
        if (fila >= 0) {
            idUsuarioSeleccionado = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString());
            txtNomUsuario.setText(tblUsuarios.getValueAt(fila, 1).toString());
            txtClave.setText(""); // Por seguridad, no traemos la clave, obligamos a escribir una nueva si modifica
            cbxRol.setSelectedItem(tblUsuarios.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnLimpiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarUsuarioActionPerformed
        // TODO add your handling code here:
        limpiarCamposUsuarios();
    }//GEN-LAST:event_btnLimpiarUsuarioActionPerformed
    private void cargarProductos() {
        // Configuramos las columnas de la tabla
        // Al crear el modelo, sobreescribimos el método isCellEditable para que retorne siempre falso
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en todas las celdas
            }
        };
        modelo.addColumn("ID");
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");

        tblProductos.setModel(modelo);

        // Consulta: Solo productos con estado = 1 (Activos)
        String sql = "SELECT id_producto, codigo_barras, nombre, precio, stock FROM Productos WHERE estado = 1";

        try (Connection conn = Conexion.conectar(); PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {

            // Recorremos los resultados y llenamos la tabla
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("id_producto");
                fila[1] = rs.getString("codigo_barras");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getDouble("precio");
                fila[4] = rs.getInt("stock");
                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarIndicadores() {
        String sqlVentas = "SELECT SUM(total) as Ingresos, COUNT(id_venta) as Transacciones, MAX(total) as Maximo, MIN(total) as Minimo, AVG(total) as Promedio FROM Ventas";
        String sqlStock = "SELECT COUNT(id_producto) as Agotados FROM Productos WHERE stock = 0 AND estado = 1";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar()) {

            // 1. Cargar métricas de Ventas
            try (java.sql.PreparedStatement pst = conn.prepareStatement(sqlVentas); java.sql.ResultSet rs = pst.executeQuery()) {

                if (rs.next()) {
                    // Si no hay ventas, la BD devuelve null, que en Java getDouble lo lee como 0.0
                    double ingresos = rs.getDouble("Ingresos");
                    int transacciones = rs.getInt("Transacciones");
                    double maximo = rs.getDouble("Maximo");
                    double minimo = rs.getDouble("Minimo");
                    double promedio = rs.getDouble("Promedio");

                    lblIngresosTotales.setText(String.format("S/ %.2f", ingresos));
                    lblTotalTransacciones.setText(String.valueOf(transacciones));
                    lblTicketMaximo.setText(String.format("S/ %.2f", maximo));
                    lblTicketMinimo.setText(String.format("S/ %.2f", minimo));
                    lblTicketPromedio.setText(String.format("S/ %.2f", promedio));
                }
            }

            // 2. Cargar alerta de Stock (Productos agotados)
            try (java.sql.PreparedStatement pstStock = conn.prepareStatement(sqlStock); java.sql.ResultSet rsStock = pstStock.executeQuery()) {

                if (rsStock.next()) {
                    int agotados = rsStock.getInt("Agotados");
                    lblAlertasStock.setText(String.valueOf(agotados));
                }
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar KPIs: " + e.getMessage(), "Error BD", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarProductos(String textoBusqueda) {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");

        tblProductos.setModel(modelo);

        // Consulta SQL con comodines (LIKE) para buscar coincidencias
        String sql = "SELECT id_producto, codigo_barras, nombre, precio, stock FROM Productos WHERE estado = 1 AND (nombre LIKE ? OR codigo_barras LIKE ?)";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // Los signos % indican que puede haber cualquier texto antes o después de la búsqueda
            pstmt.setString(1, "%" + textoBusqueda + "%");
            pstmt.setString(2, "%" + textoBusqueda + "%");

            java.sql.ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("id_producto");
                fila[1] = rs.getString("codigo_barras");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getDouble("precio");
                fila[4] = rs.getInt("stock");
                modelo.addRow(fila);
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarHistorialVentas() {
        // Cambia "modelo" por "modeloVentas"
        javax.swing.table.DefaultTableModel modeloVentas = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en todas las celdas
            }
        };
        modeloVentas.addColumn("ID Venta");
        modeloVentas.addColumn("Cliente");
        modeloVentas.addColumn("Documento");
        modeloVentas.addColumn("Método Pago");
        modeloVentas.addColumn("Total");
        modeloVentas.addColumn("Fecha");

        tblVentas.setModel(modeloVentas); // Asume que tu tabla principal se llama tblVentas

        String sql = "SELECT id_venta, cliente, documento, metodo_pago, total, fecha FROM Ventas ORDER BY fecha DESC";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pst = conn.prepareStatement(sql); java.sql.ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getInt("id_venta");
                fila[1] = rs.getString("cliente");
                fila[2] = rs.getString("documento");
                fila[3] = rs.getString("metodo_pago");
                fila[4] = rs.getDouble("total");
                fila[5] = rs.getTimestamp("fecha");
                modeloVentas.addRow(fila);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar ventas: " + e.getMessage());
        }
    }

    private void cargarProductosEliminados() {
        javax.swing.table.DefaultTableModel modeloEliminados = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en todas las celdas
            }
        };
        modeloEliminados.addColumn("ID");
        modeloEliminados.addColumn("Código");
        modeloEliminados.addColumn("Nombre del Producto");
        modeloEliminados.addColumn("Precio");
        modeloEliminados.addColumn("Stock Restante");

        tblEliminados.setModel(modeloEliminados); // Asume que tu tabla inferior se llama tblEliminados

        String sql = "SELECT id_producto, codigo_barras, nombre, precio, stock FROM Productos WHERE estado = 0";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pst = conn.prepareStatement(sql); java.sql.ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("id_producto");
                fila[1] = rs.getString("codigo_barras");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getDouble("precio");
                fila[4] = rs.getInt("stock");
                modeloEliminados.addRow(fila);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar eliminados: " + e.getMessage());
        }
    }

    private void cargarGraficoStock() {
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();

        String sql = "SELECT nombre, stock FROM Productos WHERE estado = 1 ORDER BY stock ASC LIMIT 10";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pst = conn.prepareStatement(sql); java.sql.ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                // Simplificamos la leyenda
                dataset.setValue(rs.getInt("stock"), "Unidades", rs.getString("nombre"));
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar datos del gráfico: " + e.getMessage());
            return;
        }

        org.jfree.chart.JFreeChart grafico = org.jfree.chart.ChartFactory.createBarChart(
                "Top 10: Alerta de Reposición",
                "", // Eje X vacío para que quede más limpio
                "Unidades Disponibles",
                dataset,
                org.jfree.chart.plot.PlotOrientation.HORIZONTAL,
                false, // Apagamos la leyenda inferior porque es redundante
                true,
                false
        );

        // --- AJUSTES VISUALES DEL GRÁFICO ---
        org.jfree.chart.plot.CategoryPlot plot = grafico.getCategoryPlot();
        org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) plot.getRenderer();

        // 1. Limitar el grosor al 15% del espacio máximo (evita el bloque gigante)
        renderer.setMaximumBarWidth(0.15);

        // 2. Quitar el gradiente por defecto y aplicar un color sólido (Azul acero)
        renderer.setBarPainter(new org.jfree.chart.renderer.category.StandardBarPainter());
        renderer.setSeriesPaint(0, new java.awt.Color(54, 137, 191));

        // 3. Ocultar las líneas de la cuadrícula vertical para mayor limpieza
        plot.setDomainGridlinesVisible(false);
        // ------------------------------------

        org.jfree.chart.ChartPanel panelGrafico = new org.jfree.chart.ChartPanel(grafico);
        panelGrafico.setMouseWheelEnabled(true);

        pnlGraficoStock.setLayout(new java.awt.BorderLayout());
        pnlGraficoStock.removeAll();
        pnlGraficoStock.add(panelGrafico, java.awt.BorderLayout.CENTER);
        pnlGraficoStock.validate();
        pnlGraficoStock.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnFiltrarFechas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarUsuario;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdFechaFin;
    private com.toedter.calendar.JDateChooser jdFechaInicio;
    private javax.swing.JLabel lblAlertasStock;
    private javax.swing.JLabel lblIngresosTotales;
    private javax.swing.JLabel lblTicketMaximo;
    private javax.swing.JLabel lblTicketMinimo;
    private javax.swing.JLabel lblTicketPromedio;
    private javax.swing.JLabel lblTotalTransacciones;
    private javax.swing.JPanel pnlGraficoStock;
    private javax.swing.JTable tblEliminados;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
