/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.twcorpororation.familymart.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import com.twcorpororation.familymart.dao.Conexion;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.lowagie.text.Image;

/**
 *
 * @author Luigui
 */
public class FrmCajero extends javax.swing.JFrame {

    private DefaultTableModel modeloTicket;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCajero.class.getName());

    /**
     * Creates new form FrmCajero
     */
    public FrmCajero() {
        initComponents();
        this.setLocationRelativeTo(null);

        // Asignamos un modelo estricto a la tabla del ticket
        modeloTicket = new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "PRODUCTO", "PRECIO", "CANTIDAD", "SUBTOTAL"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblTicket.setModel(modeloTicket);

        cargarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTicket = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxMetodoPago = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarCajero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatalogo = new javax.swing.JTable();
        spnCantidad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "PRECIO", "CANTIDAD", "SUBTOTAL"
            }
        ));
        jScrollPane2.setViewportView(tblTicket);

        btnQuitar.setText("QUITAR ARTICULO");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);

        btnCobrar.setText("Cobrar y Emitir Boleta");
        btnCobrar.addActionListener(this::btnCobrarActionPerformed);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotal.setText("TOTAL: S/ 0.00 ");

        jLabel1.setText("Cliente:");

        txtCliente.addActionListener(this::txtClienteActionPerformed);

        jLabel3.setText("DNI/RUC:");

        jLabel4.setText("Forma de Pago:");

        cbxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Yape/Plin" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMetodoPago, 0, 100, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCobrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal)))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jLabel2.setText("Buscar Producto:");

        txtBuscarCajero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCajeroKeyReleased(evt);
            }
        });

        tblCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCatalogo);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblTicket.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto del ticket para quitarlo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Removemos la fila seleccionada del modelo de la tabla
        modeloTicket.removeRow(filaSeleccionada);

        // Recalculamos el total automáticamente
        calcularTotal();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblCatalogo.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto del catálogo.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener cantidad del Spinner (cambia spnCantidad por el nombre real de tu spinner, ej. jSpinner1)
        int cantidad = (Integer) spnCantidad.getValue();

        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
            return;
        }

        int stockDisponible = Integer.parseInt(tblCatalogo.getValueAt(filaSeleccionada, 4).toString());
        if (cantidad > stockDisponible) {
            JOptionPane.showMessageDialog(this, "Stock insuficiente. Solo quedan " + stockDisponible + " unidades.");
            return;
        }

        // Extraer datos del catálogo
        String id = tblCatalogo.getValueAt(filaSeleccionada, 0).toString();
        String nombre = tblCatalogo.getValueAt(filaSeleccionada, 2).toString();
        double precio = Double.parseDouble(tblCatalogo.getValueAt(filaSeleccionada, 3).toString());
        double subtotal = precio * cantidad;

        // Añadir fila al ticket
        Object[] filaTicket = new Object[5];
        filaTicket[0] = id;
        filaTicket[1] = nombre;
        filaTicket[2] = precio;
        filaTicket[3] = cantidad;
        filaTicket[4] = subtotal;

        modeloTicket.addRow(filaTicket);
        calcularTotal();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscarCajeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCajeroKeyReleased
        // TODO add your handling code here:
        buscarCatalogo(txtBuscarCajero.getText().trim());
    }//GEN-LAST:event_txtBuscarCajeroKeyReleased

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        if (tblTicket.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ticket está vacío. Agregue productos primero.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombreCliente = txtCliente.getText().trim();
        String documentoCliente = txtDocumento.getText().trim();
        String metodoPago = cbxMetodoPago.getSelectedItem().toString();

        // 1. Calcular total previo
        double totalVenta = 0.0;
        for (int i = 0; i < tblTicket.getRowCount(); i++) {
            totalVenta += Double.parseDouble(tblTicket.getValueAt(i, 4).toString());
        }

        // 2. Lógica de Base de Datos (Insertar Venta, Detalles y Actualizar Stock)
        String sqlVenta = "INSERT INTO Ventas (cliente, documento, metodo_pago, total) VALUES (?, ?, ?, ?)";
        String sqlDetalle = "INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (?, ?, ?, ?, ?)";
        String sqlActualizarStock = "UPDATE Productos SET stock = stock - ? WHERE id_producto = ?";

        int idVentaGenerada = 0;

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar()) {
            conn.setAutoCommit(false); // Iniciamos transacción segura

            // Guardar Cabecera
            try (java.sql.PreparedStatement pstmtVenta = conn.prepareStatement(sqlVenta, java.sql.Statement.RETURN_GENERATED_KEYS)) {
                pstmtVenta.setString(1, nombreCliente.isEmpty() ? "Público General" : nombreCliente);
                pstmtVenta.setString(2, documentoCliente.isEmpty() ? "00000000" : documentoCliente);
                pstmtVenta.setString(3, metodoPago);
                pstmtVenta.setDouble(4, totalVenta);
                pstmtVenta.executeUpdate();

                java.sql.ResultSet rsKeys = pstmtVenta.getGeneratedKeys();
                if (rsKeys.next()) {
                    idVentaGenerada = rsKeys.getInt(1);
                }
            }

            // Guardar Detalles y restar Stock
            try (java.sql.PreparedStatement pstmtDetalle = conn.prepareStatement(sqlDetalle); java.sql.PreparedStatement pstmtStock = conn.prepareStatement(sqlActualizarStock)) {

                for (int i = 0; i < tblTicket.getRowCount(); i++) {
                    int idProducto = Integer.parseInt(tblTicket.getValueAt(i, 0).toString());
                    int cantidad = Integer.parseInt(tblTicket.getValueAt(i, 3).toString());
                    double precio = Double.parseDouble(tblTicket.getValueAt(i, 2).toString());
                    double subtotal = Double.parseDouble(tblTicket.getValueAt(i, 4).toString());

                    // Insertar Detalle
                    pstmtDetalle.setInt(1, idVentaGenerada);
                    pstmtDetalle.setInt(2, idProducto);
                    pstmtDetalle.setInt(3, cantidad);
                    pstmtDetalle.setDouble(4, precio);
                    pstmtDetalle.setDouble(5, subtotal);
                    pstmtDetalle.executeUpdate();

                    // Restar Stock
                    pstmtStock.setInt(1, cantidad);
                    pstmtStock.setInt(2, idProducto);
                    pstmtStock.executeUpdate();
                }
            }
            conn.commit(); // Confirmar cambios en BD
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la transacción: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Abortar si falla la base de datos
        }

        // 3. Generar PDF
        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home") + "/Desktop/Boleta_FamilyMart_" + idVentaGenerada + ".pdf";
            PdfWriter.getInstance(documento, new FileOutputStream(ruta));
            documento.open();

            try {
                Image logo = Image.getInstance("src/main/resources/img/logo.png");
                logo.scaleToFit(100, 100);
                logo.setAlignment(Image.ALIGN_CENTER);
                documento.add(logo);
            } catch (Exception e) {
                System.err.println("No se cargó el logo: " + e.getMessage());
            }

            documento.add(new Paragraph("=== MINIMARKET FAMILY MART ==="));
            documento.add(new Paragraph("Ticket Nro: " + String.format("%06d", idVentaGenerada)));
            documento.add(new Paragraph("Fecha: " + new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date())));
            documento.add(new Paragraph("Cliente: " + (nombreCliente.isEmpty() ? "Público General" : nombreCliente)));
            documento.add(new Paragraph("DNI/RUC: " + (documentoCliente.isEmpty() ? "00000000" : documentoCliente)));
            documento.add(new Paragraph("Forma de Pago: " + metodoPago));
            documento.add(new Paragraph("--------------------------------------------------"));
            documento.add(new Paragraph("CANT.  |  PRODUCTO  |  SUBTOTAL"));
            documento.add(new Paragraph("--------------------------------------------------"));

            for (int i = 0; i < tblTicket.getRowCount(); i++) {
                String nombre = tblTicket.getValueAt(i, 1).toString();
                String precio = tblTicket.getValueAt(i, 2).toString();
                String cantidad = tblTicket.getValueAt(i, 3).toString();
                String subtotal = tblTicket.getValueAt(i, 4).toString();
                documento.add(new Paragraph(cantidad + " x " + nombre + " (S/" + precio + ") = S/ " + subtotal));
            }

            documento.add(new Paragraph("--------------------------------------------------"));
            documento.add(new Paragraph(String.format("TOTAL A PAGAR: S/ %.2f", totalVenta)));
            documento.add(new Paragraph("¡Gracias por su compra!"));
            documento.close();

            javax.swing.JOptionPane.showMessageDialog(this, "Venta Exitosa. Ticket Nro " + idVentaGenerada + " generado.");

            // 4. Limpiar UI y Actualizar Catálogo
            modeloTicket.setRowCount(0);
            calcularTotal();
            txtCliente.setText("");
            txtDocumento.setText("");
            cbxMetodoPago.setSelectedIndex(0);
            cargarCatalogo();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        // Llama de vuelta a la ventana de Login
        com.twcorpororation.familymart.FrmLogin login = new com.twcorpororation.familymart.FrmLogin();
        login.setVisible(true);
        
        // Destruye la ventana actual para liberar memoria
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void buscarCatalogo(String textoBusqueda) {
        javax.swing.table.DefaultTableModel modeloCat = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición
            }
        };
        modeloCat.addColumn("ID");
        modeloCat.addColumn("Código");
        modeloCat.addColumn("Nombre");
        modeloCat.addColumn("Precio");
        modeloCat.addColumn("Stock");

        tblCatalogo.setModel(modeloCat);

        String sql = "SELECT id_producto, codigo_barras, nombre, precio, stock FROM Productos WHERE estado = 1 AND stock > 0 AND (nombre LIKE ? OR codigo_barras LIKE ?)";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, "%" + textoBusqueda + "%");
            pstmt.setString(2, "%" + textoBusqueda + "%");

            java.sql.ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("id_producto");
                fila[1] = rs.getString("codigo_barras");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getDouble("precio");
                fila[4] = rs.getInt("stock");
                modeloCat.addRow(fila);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }

    private void calcularTotal() {
        double total = 0.0;
        for (int i = 0; i < tblTicket.getRowCount(); i++) {
            Object valorCelda = tblTicket.getValueAt(i, 4); // Índice 4 es la columna Subtotal

            // Solo sumamos si la celda tiene un valor real
            if (valorCelda != null && !valorCelda.toString().trim().isEmpty()) {
                total += Double.parseDouble(valorCelda.toString());
            }
        }
        lblTotal.setText(String.format("TOTAL: S/ %.2f", total));
    }

    private void cargarCatalogo() {
        javax.swing.table.DefaultTableModel modeloCat = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición
            }
        };
        modeloCat.addColumn("ID");
        modeloCat.addColumn("Código");
        modeloCat.addColumn("Nombre");
        modeloCat.addColumn("Precio");
        modeloCat.addColumn("Stock");

        // Asumiendo que tu tabla izquierda se llama tblCatalogo
        tblCatalogo.setModel(modeloCat);

        String sql = "SELECT id_producto, codigo_barras, nombre, precio, stock FROM Productos WHERE estado = 1 AND stock > 0";

        try (Connection conn = Conexion.conectar(); PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("id_producto");
                fila[1] = rs.getString("codigo_barras");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getDouble("precio");
                fila[4] = rs.getInt("stock");
                modeloCat.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCajero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cbxMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblCatalogo;
    private javax.swing.JTable tblTicket;
    private javax.swing.JTextField txtBuscarCajero;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
