/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.twcorpororation.familymart;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Luigui
 */
public class FrmLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        cbxRol = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña");

        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnIngresar.setText("Iniciar Sesión");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero" }));
        cbxRol.addActionListener(this::cbxRolActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresar)))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnIngresar))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (validarContrasenaFuerte(password)) {
            // Consulta SQL para insertar el usuario
            String sql = "INSERT INTO Usuarios (username, password, id_rol, estado) VALUES (?, ?, ?, 1)";

            try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, usuario);
                pstmt.setString(2, password); // Nota: En un entorno de producción real, las contraseñas se encriptan (ej. con BCrypt).

                // Obtenemos el rol seleccionado (Índice 0 = Admin, Índice 1 = Cajero)
                // Le sumamos 1 porque en nuestra BD los IDs empiezan en 1
                int idRol = cbxRol.getSelectedIndex() + 1;
                pstmt.setInt(3, idRol);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar en la BD: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "La contraseña no cumple con los requisitos mínimos:\n"
                    + "- Mínimo 8 caracteres\n"
                    + "- Una letra mayúscula y una minúscula\n"
                    + "- Un número\n"
                    + "- Un símbolo especial (@$!%*?&)",
                    "Seguridad de Contraseña", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword());

        // Consulta SQL para buscar al usuario activo
        String sql = "SELECT id_rol FROM Usuarios WHERE username = ? AND password = ? AND estado = 1";

        try (java.sql.Connection conn = com.twcorpororation.familymart.dao.Conexion.conectar(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, usuario);
            pstmt.setString(2, password);

            java.sql.ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                int idRol = rs.getInt("id_rol");

                if (idRol == 1) {
                    JOptionPane.showMessageDialog(this, "Bienvenido Administrador");

                    // Instancia la ventana FrmAdmin usando su ruta de paquete
                    com.twcorpororation.familymart.vistas.FrmAdmin admin = new com.twcorpororation.familymart.vistas.FrmAdmin();
                    admin.setVisible(true); // Hace visible el panel de pestañas

                    // Cierra la ventana de Login para que no quede en segundo plano
                    this.dispose();

                } else if (idRol == 2) {
                    JOptionPane.showMessageDialog(this, "Bienvenido Cajero");
                    com.twcorpororation.familymart.vistas.FrmCajero cajero = new com.twcorpororation.familymart.vistas.FrmCajero();
                    cajero.setVisible(true);
                    // Aquí pondremos el FrmCajero cuando lo creemos
                    this.dispose();
                }

                // Cerramos la ventana de Login
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos, o cuenta inactiva.", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            }

        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cbxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRolActionPerformed
        // TODO add your handling code here:
        // Limpiar los campos de texto al cambiar de rol
        txtUsuario.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_cbxRolActionPerformed

// ... dentro de la clase FrmLogin ...
    /**
     * Valida que la contraseña cumpla con: - Mínimo 8 caracteres - Al menos una
     * minúscula - Al menos una mayúscula - Al menos un número - Al menos un
     * carácter especial (@$!%*?&)
     */
    private boolean validarContrasenaFuerte(String password) {
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
